version: "3.9"

services:
  # eshop-frontend:
  #   container_name: eshop-frontend
  #   build:
  #     context: ./frontend
  #   restart: always
  #   ports:
  #     - "8000:80"
  #   # probably volume only for development?
  #   volumes:
  #     - ./frontend/src:/usr/local/apache2/htdocs/
  #   networks:
  #     - products
    
  # eshop-frontend-react:
  #   container_name: eshop-frontend-react
  #   build: ./frontend-react
  #   volumes:
  #     - ./frontend-react:/app

  mysql-kc:
    container_name: mysql-kc
    image: mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      # The user, password and database that Keycloak
      # is going to create and use
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: keycloak_db
      # Self-Explanatory
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql-kc-volume:/var/lib/mysql
    networks:
      - kc-mysql-network

  keycloak-w:
    container_name: keycloak-w
    image: jboss/keycloak
    ports:
      - 8182:8080
    restart: unless-stopped
    environment:
      # User and password for the Administration Console
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mysql
      DB_ADDR: mysql-kc
      DB_PORT: 3306
      # Same values as the mysql-kc service
      DB_USER: admin
      DB_PASSWORD: admin
      DB_DATABASE: keycloak_db
    depends_on:
      - mysql-kc
    volumes:
      - keycloak-realm-data:/opt/jboss/keycloak/standalone/data
      # - ./standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
    networks:
      - kc-mysql-network

  orders_db: 
    image: mysql
    ports: 
      - "3308:3306"
    expose:
      # Opens port 3306 on the container
      - 3308
    container_name: orders_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: orders_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin 
    volumes:
      - ./data/orders-db:/var/lib/mysql   
    networks:
      - orders
  
  products_db:
    container_name: products_db
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: products_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3310:3306'
    expose:
      # Opens port 3306 on the container
      - '3310'
      # Where our data will be persisted
    volumes:
      - ./data/products-db:/var/lib/mysql
    networks:
      - products


networks:
  kc-mysql-network:
  products:
  orders:

volumes:
  mysql-kc-volume:
  keycloak-realm-data:
  orders-db:
  products-db: